name: Hello world #name cua workflow 
on: #chay khi nao
  push:
    branches: [main]
jobs: # nhung job can chay
  say-hi: # id job
    runs-on: ubuntu-latest # chay tren nen tang nao
    step:
      -run: echo Hello world

       