name: Hello world #name cua workflow 
on: #chay khi nao
  push:
    paths:
      - '!README.md'
      - '!docs/**'
      - '**.js'
    branches: 
      - 'main'
      - 'release/**'
      - '!dev/**'
  pull_request:
     type: [opened]
     branches: [main]
jobs: # nhung job can chay
  say-hi: # id job
    runs-on: ubuntu-latest # chay tren nen tang nao
    steps:
      - run: echo "TODAY=22/09/2000" >> $GITHUB_ENV
      - run: echo Hello world
      - run: echo Today is $TODAY

       